name: core_analysis
version: 0.3.8
repository: https://github.com/bestow-code/core_analysis
description: Dart analysis_options for Core projects
environment: 
  sdk: '>=3.0.0 <4.0.0'
dependencies: 
  very_good_analysis: ^5.1.0
