name: core_analysis
version: 0.1.0+1
publish_to: https://onepub.dev/api/ffuuhnofly/
description: Dart analysis_options for Core projects
environment: 
  sdk: '>=3.0.0 <4.0.0'
dependencies: 
  very_good_analysis: ^5.1.0
