name: analyze
on:
  push:
permissions:
  pull-requests: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: dart analyze .
