on:
#  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: dart-lang/setup-dart@v1

#      - name: Install onepub
#        run: dart pub global activate onepub
#      - run: onepub import
#        env:
#          ONEPUB_TOKEN: ${{ secrets.onepub_token }}
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.release_please_token }}
          release-type: dart
#      - name: Add automerge label
#        if: steps.release.outputs.prs
#        uses: actions/github-script@v6
#        with:
#          github-token: ${{secrets.GITHUB_TOKEN}}
#          script: |
#            github.rest.issues.addLabels({
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              issue_number: ${{ steps.release.outputs.pr }},
#              labels: ['automerge']
#            })
      - name: Enable Pull Request Automerge
        run: gh pr merge --merge --auto ${{ steps.release.outputs.pr.number }}
        env:
          GH_TOKEN: ${{ secrets.release_please_token }}
