name: test
on:
  push:
permissions:
  pull-requests: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: dart-lang/setup-dart@v1
      - name: Install Dependencies
        run: dart pub get
      - name: Test
        run: dart test
